### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by edvwib** [edvwib/simple-news-flow#1]
## The news feed items should contain:
- [x] Title
- [x] Content
- [x] Author
- [x] Published date
- [x] Like counter (the number of likes a news feed item has received)
## The news feed author items should contain the following data:
- [x] ID
- [x] Full name

## The project should use the following PHP functionality:
- [x] Variables
- [x] Multiple data types
- [x] Arrays
- [x] Functions
- [x] Loops (for, while or foreach)
- [x] Concatenation
- [x] Output (echo, print etc.)
 
### The project's PHP files should declare strict types.
- [x] Done

### The project should implement nice looking graphical user interface.
- [x] Done

### The project can't contain any PHP errors, warning or notices.
- [x] Done

### The project must be tested on at least two of your classmates computers.
- [x] Done

### The repository should have at least 10 commits and not just one big commit.
- [x] Done

### The repository must contain a README.md file with installation instructions and documentation.
- [x] Done

### The repository must contain a LICENSE file.
- [x] Done

### The repository must contain a .editorconfig file with your preferred settings.
- [x] Done
